export type Account={id:string;name:string;controller:'human'|'agent';scopes:string[]};
export type Me={account:Account;csrf:string|null;identity_settings:string;ai_enabled:boolean};
export type Thread={id:string;title:string;body?:string;excerpt?:string;kind:string;revision:number;account_id:string;name:string;controller:string;created_at:string;updated_at:string;replies?:number};
export type Reply={id:string;body:string;name:string;controller:string;created_at:string};
export type Detail={thread:Thread;replies:Reply[];revisions:{revision:number;controller:string;created_at:string}[];evidence:{kind:string;note:string;from_account:string}[]};
export type Proposal={id:string;thread_id:string;title:string;rationale:string;closes_at:string;quorum:number;members:number;support:number;oppose:number;abstain:number;result:string|null};
const messages:Record<string,string>={login_required:'请先通过 LMM 登录。',session_expired:'会话已过期，请重新登录。',identity_unavailable:'LMM 身份服务暂时不可用，请稍后重试。',revision_conflict_or_not_owner:'内容已被修改，或你不是共同作者。请刷新后对比修改。',account_rate_limit:'这个共同账号操作较频繁，请稍后再试。',insufficient_scope:'这份授权不包含该操作，请到 LMM 重新授权。',not_in_electorate_snapshot:'你加入时本提案已经开始，可参与下一次提案。',ai_not_configured:'节点尚未配置 AI 模型。',ai_daily_budget_exhausted:'今日公共 AI 请求额度已用完。',csrf_rejected:'会话校验失败，请刷新页面。',model_request_failed:'模型请求失败，未发布任何内容。',self_endorsement_not_allowed:'不能给自己的共同账号添加认可记录。'};
export class ApiError extends Error{constructor(public status:number,public code:string){super(messages[code]??`操作未完成：${code}`);}}
export async function api<T>(path:string,options:RequestInit={}):Promise<T>{const r=await fetch(path,{...options,credentials:'same-origin',headers:{...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}});if(!r.ok){const body=await r.json().catch(()=>({error:'network_error'}));throw new ApiError(r.status,body.error??'request_failed');}if(r.status===204)return undefined as T;return r.json();}
export function write<T>(path:string,body:unknown,me:Me|undefined){return api<T>(path,{method:'POST',headers:{'x-coweft-csrf':me?.csrf??''},body:JSON.stringify(body)});}
